---
title: "XAI3_v1"
author: "Hajar Abdoun"
date: "13/5/2022"
output: html_document
---

## EXERCISE:

Apply PDP to the regression example of predicting bike rentals. Fit a random forest approximation for the prediction of bike rentals (**cnt**). Use the partial dependence plot to visualize the relationships the model learned. Use the slides shown in class as model.  

## QUESTION:

Analyse the influence of **days since 2011, temperature, humidity** and **wind speed** on the predicted bike counts.


```{r}
library(dplyr)
library(plotly)
library(reshape2)
library(lubridate)
library(randomForestSRC)

#setwd("/Users/cmonserr/OneDrive - UPV/Trabajo_2/Asignaturas/Evaluacion de modelos/Practicas/Practica 3/Bike-Sharing-Dataset")
days <- read.csv("day.csv")
hour <- read.csv("hour.csv")

days$dteday <- as_date(days$dteday)
days_since <- select(days, workingday, holiday, temp, hum, windspeed, cnt)
days_since$days_since_2011 <- int_length(interval(ymd("2011-01-01"), days$dteday)) / (3600*24)
days_since$SUMMER <- ifelse(days$season == 3, 1, 0)
days_since$FALL <- ifelse(days$season == 4, 1, 0)
days_since$WINTER <- ifelse(days$season == 1, 1, 0)
days_since$MISTY <- ifelse(days$weathersit == 2, 1, 0)
days_since$RAIN <- ifelse(days$weathersit == 3 | days$weathersit == 4, 1, 0)
days_since$temp <- days_since$temp * 47 - 8
days_since$hum <- days_since$hum * 100
days_since$windspeed <- days_since$windspeed * 67

rf <- rfsrc(cnt~., data=days_since)

results <- select(days_since, days_since_2011, temp, hum, windspeed, cnt)
nr <- nrow(days_since)
for(c in names(results)[1:4])
{
  for(i in 1:nr){
    r <- days_since
    r[[c]] <- days_since[[c]][i]
    sal <- predict(rf, r)$predicted
    results[[c]][i] <- sum(sal) / nr
  }
}

p1 = ggplot(days_since, aes(x = temp, y = results$temp)) + ylim(0, 6000) + geom_line() + geom_rug(sides="b", alpha = 0.5) + labs(x = "Temperature")

p2 = ggplot(days_since, aes(x = hum, y = results$hum)) + ylim(0, 6000) + geom_line() + geom_rug(sides="b", alpha = 0.5) + labs(x = "Humidity")

p3 = ggplot(days_since, aes(x = days_since_2011, y = results$days_since_2011)) + ylim(0, 6000) + geom_line() + geom_rug(sides="b", alpha = 0.5) + labs(x = "Days since 2011", y = "Predictions")

p4 = ggplot(days_since, aes(x = windspeed, y = results$windspeed)) + ylim(0, 6000) + geom_line() + geom_rug(sides="b", alpha = 0.5) + labs(x = "Windspeed")
#p1
subplot(p3, p1, p2, p4, titleX = TRUE, titleY = TRUE, shareX = FALSE, shareY = TRUE)
```
Days since 2011: as time goes by, there is generally a clear upward trend in bicycle rentals, although in the last few days the predictions are decreasing. 

Temperature: The number of rented bicycles increases with the temperature up to around 20 degrees Celsius, but then decreases as the temperature rises from around 25 degrees Celsius onwards. 

Humidity: up to 50% humidity, the number of rented bicycles remains constant, but then decreases inversely to the increase in humidity. 

Windspeed: the prediction for bicycle rentals decreases gradually until a wind speed of approximately 23 km/h is reached. At this point, the predictions are constant.
